name: 'Buf action'

inputs:
  github-token:
    description: 'GitHub token to use for publishing the package. Use "secrets.GITHUB_TOKEN"'
    required: true
  target-directory:
    description: 'The target directory for runing buf lint'
    default: protobuf
  language:
    description: 'The target language for generation'
    default: go #우선은 go를 기본값으로 설정

runs:
  using: "composite"
  steps:
    - name: Install Buf CLI
      uses: bufbuild/buf-setup-action@v1
      with:
        version: "1.28.1"

    # Check installation Buf CLI completed successfully and Buf version
    - name: Check Buf version
      shell: bash
      run: buf --version

    # Run Buf lint
    - name: Run buf lint
      shell: bash
      run:  |
        cd ${{ inputs.target-directory }}
        buf lint
