name: Buf
description: Lint gRPC schema files with buf, check breaking changes, and generate and build Go codes.

inputs:
  input-directory:
    description: 'Directory where the `*.proto` files reside. (default: "./protobuf")'
    default: './protobuf'
  buf-version:
    description: 'The version of the buf cli to use. (ex: "latest", "1.28.0", default: "1.28.1")'
    default: 1.28.1
  go-version:
    description: 'The version of golang to use (default: "1.20")'
    default: '1.20'

runs:
  using: composite
  steps:
    - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # 6.5.0
      with:
        go-version: ${{ inputs.go-version }}

    - uses: bufbuild/buf-setup-action@a47c93e0b1648d5651a065437926377d060baa99 # 1.50.0
      with:
        version: ${{ inputs.buf-version }}

    - shell: bash
      working-directory: ${{ inputs.input-directory }}
      env:
        INPUT_DIRECTORY: ${{ inputs.input-directory }}
      run: |
        # Lint .proto codes
        buf lint

        # Check if there's any breaking changes. It checks backword
        # compatibility of "${INPUT_DIRECTORY}/*.proto" againt
        # origin/main branch
        buf breaking --against "${GITHUB_WORKSPACE}/.git#branch=origin/main,subdir=${INPUT_DIRECTORY}"

        # Run `buf generate`
        SLUG=$("${GITHUB_ACTION_PATH}/repository-to-slug" "${GITHUB_REPOSITORY}")
        buf generate --template "$("${GITHUB_ACTION_PATH}/generate-template" "${RUNNER_TEMP}/buf" "${SLUG}")"
        # Build result will be stored at: "${RUNNER_TEMP}/buf/github.com/portone-io/go/interface/${SLUG}"
        (
          cd "${RUNNER_TEMP}/buf"
          find . -type f
        )

        (
          cd "${RUNNER_TEMP}/buf/github.com/portone-io/go/interface/${SLUG}"
          go mod init "github.com/portone-io/go/interface/${SLUG}"
          go mod tidy
          go build ./...
        )
