#!/usr/bin/env python3
from sys import argv
from re import fullmatch, X

def show_help_then_fail():
    print(f'''\
Usage: {argv[0]} <target-dir> <service-name>

Sample:
  {argv[0]} ../generate portone-io/merchant-service-interface   #=> 'merchant' will be used as name
  {argv[0]} ../generate portone-io/platform-service             #=> 'platform' will be used as name
  {argv[0]} ../output portone-io/corewebhook-interface          #=> 'corewebhook' will be used as name\
''')
    exit(1)

# Fail if no argument is given
if len(argv) != 3:
    show_help_then_fail()

tempdir = argv[1]

# The owner name (username + org name) may only contain: alphanumeric characters
# or single hyphens, and cannot begin or end with a hyphen.
#
# The repository name can only contain ASCII letters, digits, and the characters
# ., -, and _.
result = fullmatch(r'''
^
    (?:[a-zA-Z0-9][a-zA-Z0-9-]*[a-zA-Z0-9]) # owner name
    /
    (?P<slug>[a-zA-Z0-9._-]+?)-(?:service|interface|service-interface)? # repository name
$
''', argv[2], X)

# Fail if the argument is not a valid GitHub repository name
if result is None:
    show_help_then_fail()

slug = result.group('slug')

print(f'''\
version: v1
managed:
  enabled: true
  go_package_prefix:
    default: github.com/portone-io/go/interface/{slug}
    except:
      - buf.build/googleapis/googleapis
plugins:
  - plugin: buf.build/protocolbuffers/go:v1.28.1
    out: {tempdir}
  - plugin: buf.build/grpc/go
    out: {tempdir}
''')
