#!/usr/bin/env python3
from sys import argv

if len(argv) != 3:
    print(f'''\
Usage: {argv[0]} <target-dir> <slug>

Sample:
  {argv[0]} ../generate merchant
  {argv[0]} ../generate platform
  {argv[0]} ../output corewebhook\
''')
    exit(1)

_, tempdir, slug = argv

print(f'''\
version: v1
managed:
  enabled: true
  go_package_prefix:
    default: github.com/portone-io/go/interface/{slug}
    except:
      - buf.build/googleapis/googleapis
plugins:
  - plugin: buf.build/protocolbuffers/go:v1.28.1
    out: {tempdir}
  - plugin: buf.build/grpc/go
    out: {tempdir}
''')
