name: Buf go build
description: Build gRPC schema files into Go codes with buf and publish them to the portone-io/go repository.

inputs:
  input-directory:
    description: 'Directory where the `*.proto` files reside. (default: "./protobuf")'
    default: './protobuf'
  buf-version:
    description: 'The version of the buf cli to use. (ex: "latest", "1.28.0", default: "1.28.1")'
    default: 1.28.1
  deploy-key:
    description: 'Deploy key (OpenSSH private key) which have write permission to portone-io/go repository'
    required: true
  go-version:
    description: 'The version of golang to use (default: "1.20")'
    default: '1.20'

runs:
  using: composite
  steps:
    - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # 6.5.0
      with:
        go-version: ${{ inputs.go-version }}

    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # 7.0.0
      with:
        repository: portone-io/go
        path: __go__
        ssh-key: ${{ inputs.deploy-key }}
        persist-credentials: false

    - uses: bufbuild/buf-setup-action@a47c93e0b1648d5651a065437926377d060baa99 # 1.50.0
      with:
        version: ${{ inputs.buf-version }}

    - uses: webfactory/ssh-agent@e83874834305fe9a4a2997156cb26c5de65a8555 # 0.10.0
      with:
        ssh-private-key: ${{ inputs.deploy-key }}

    - shell: bash
      working-directory: ${{ inputs.input-directory }}
      run: |
        set -x

        # Run `buf generate`
        SLUG=$("${GITHUB_ACTION_PATH}/repository-to-slug" "${GITHUB_REPOSITORY}")
        buf generate --template "$("${GITHUB_ACTION_PATH}/generate-template" "${RUNNER_TEMP}/buf" "${SLUG}")"
        # Build result will be stored at: "${RUNNER_TEMP}/buf/github.com/portone-io/go/interface/${SLUG}"
        (
          cd "${RUNNER_TEMP}/buf"
          find . -type f
        )

        # Go to portone-io/go repository
        cd "${GITHUB_WORKSPACE}/__go__"
        mkdir -p interface

        # Replace previous build result with new one
        rm -rf "interface/${SLUG}"
        mv "${RUNNER_TEMP}/buf/github.com/portone-io/go/interface/${SLUG}" ./interface/
        (
          cd "./interface/${SLUG}"
          go mod init "github.com/portone-io/go/interface/${SLUG}"
          go mod tidy
          git config --global url."ssh://git@github.com/".insteadOf https://github.com/
          go env -w GOPRIVATE='github.com/portone-io/*'
          go build ./...
        )

        # Early-return if there's nothing to commit
        git add -A
        if git diff --quiet --staged --exit-code; then
          echo "No changes to commit"
          exit
        fi

        # Parse git-ls-remote(1) output to determine the current latest tag for
        # a given slug, then check if given tag from github.ref is newer than
        # the latest tag. It fails if given github.ref is not a tag or if it is
        # older than the latest tag.
        VERSION=$(
          git ls-remote --tags --refs origin |
          "${GITHUB_ACTION_PATH}/check-version" "${SLUG}" "${GITHUB_REF}"
        )

        git config user.name github-actions
        git config user.email github-actions@github.com
        git commit -m "interface/${SLUG}: ${VERSION}"
        git tag "interface/${SLUG}/v${VERSION}"
        git push --atomic origin main "interface/${SLUG}/v${VERSION}"
